### ISSUE TITLE
Support release asset upload

### ISSUE THREAD

**Issue by xakraz** [johnmanjiro13/gh-bump#102]
Hi @johnmanjiro13 👋🏻 

First, thanks for your extension, it is really useful for me on a daily basis.

One thing I am wondering is if it could also support assets upload to the release.

I know that this is a built-in feature of the GH cli but we face some kind of issue where
* We use `gh-bump` to create the new Tag + Release
* We use `gh` to upload the assets

But in the time between, a GitHub workflow has been triggered by the Tag pushed and fails since the assets are not there yet 😅 

Have you some tips for us in that regard?

Many thanks 🙏🏻

**Comment by johnmanjiro13** [comment]
Hi @xakraz.
Thank you for your report. I understood the issue.

If you could upload assets at the same time you create the new release, I think that would solve the problem.
According to the document, `gh release create` accepts asset files.
https://cli.github.com/manual/gh_release_create

`gh-bump` hasn't supported it yet, but we can add an option to pass files (e.g. `--files`).

**Comment by johnmanjiro13** [comment]
[v0.9.0](https://github.com/johnmanjiro13/gh-bump/releases/tag/v0.9.0) has been released.
You can upload assets using the `--asset-files` option.

```
$ gh bump --asset-files file1,file2

or

$ gh bump --asset-files file1 --asset-files file2
```

**Comment by xakraz** [comment]
Thank you so much @johnmanjiro13 🙏🏻
